name: Internal CI Checks
# This workflows checks if the author of a PR is a member of the CodeQL team
# and adds `ready-for-internal-ci` label to trigger the internal CI

on:
  pull_request_target:

jobs:
  set-label:
    runs-on: ubuntu-latest
    steps:
      - name: Set a label to trigger internal CI checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USERNAME="${{ github.event.pull_request.user.login }}"
          LABEL="ready-for-internal-ci"
          set +eo pipefail
          echo "Checking if user $USERNAME is a member of the CodeQL team"
          gh api -H "Accept: application/vnd.github+json" /orgs/github/teams/codeql/memberships/$USERNAME > /dev/null 2>&1
          if [ "$?" == 0 ]; then
              echo "User $USERNAME is a member of the CodeQL team"
              echo "Adding 'ready-for-internal-ci' label"
              gh pr edit "${{ github.event.pull_request.number }}" --repo $GITHUB_REPOSITORY --add-label $LABEL
          else
            echo "User $USERNAME is not a member of the CodeQL team"
            echo "To trigger the internal CI, a maintainer needs to add the ready-for-internal-ci label"
          fi